### PR TITLE
Updates for Using Python Page

### PR DESCRIPTION
**Pull request by ianhi**
Two main commits to look at here:

1. https://github.com/micro-manager/micro-manager.github.io/commit/aac416c1227802ae234c12c446a345428759f797
Updates the description of available libraries following the thoughts  in #90. In particular would be good to get input from: 
 @fdrgsp, @tlambert03 and @henrypinkard (and maybe @oeway has a library to add here?)

2. https://github.com/micro-manager/micro-manager.github.io/commit/debee6d5917abdac9d8c867898989b458afd33d9
Updates the MMCorePy tutorial to use pymmcore. I also refreshed or expanded on good chunk (but not all) of the content. I guess @marktsuchida would be a good person to look at this commit.

finally https://github.com/micro-manager/micro-manager.github.io/commit/e2478d5ce0049d21a6bf78d499c64cf5b01a9823 just makes it nicer to run the jekyll docs locally.

### CODE REVIEW

**Comment by henrypinkard** [comment]
I think if you're going to add this level of detail, it should be written towards a user perspective, rather than a developer perspective as it is now. Less about programming language concepts, and more about what you the user can do with them.

- Is it worth just dropping MMCorepy altogether at this point?
- I would advocate for keeping pyrco-manager first on  there as I had originally written it, because in my experience there seems to be a large python user base of non-developers who is familiar with using micro-manager and just wants to do something minimal through python like call an API function, have easy access to data, start some microfluidics, etc. These people don't know about c++/Java architectures, bindings, event loops, etc., and so it would make more sense to leave that complexity for those who continue reading down.
- For those that do read down I think this can be written in a way that more clearly delineates the differences between pymmcore and pycromanager. The way its written right now makes it sound like pycromanger, but not pymmcore requires you to launch the application (no the longer the case with headless mode), install java yourself (comes bundled for most systems, unless new installers are added ), or access the core (both do this, with different mechanisms).

**Comment by marktsuchida** [comment]
Appreciate it. All looks good to me. Maybe add that `pip` also works to install `pymmcore` for people who are not using conda for some reason.

I'm fine with pycro-manager being at the top of the list -- it has a wider audience. MMCorePy should probably not be presented as one of 3 main libraries, but its name could be mentioned once as the predecessor to pymmcore so that people crawling out from under a rock can orient themselves.

**Review by tlambert03 — APPROVED** [review]
i think the changes look great.  thanks @ianhi

**Comment by ianhi** [comment]
re ordered and added a comment about pip install. @henrypinkard can you make a suggestion of what to the pycromananger description?

**Comment by ianhi** [comment]
> The way its written right now makes it sound like pycromanger, but not pymmcore requires you to launch the application (no the longer the case with headless mode),

From my POV launching the micro-manager gui is a killer feature of pycromanager. Like you note it really lowers the barrier to entry for a new user to interface with python because they can still mostly control things from GUI they are used to. For headless mode however is there a reason to prefer pycromanager over pymmcore(-plus)? The faster data access and removal of ZMQ from the stack make pymmcore more appealing to me for that. (throwback to https://github.com/micro-manager/pycro-manager/issues/132)

**Comment by tlambert03** [comment]
Personally, I tend to agree very much with @ianhi, that the killer feature of pycro-manager is that it works directly with the existing MM gui. I also agree with https://github.com/micro-manager/pycro-manager/issues/132#issuecomment-731881340, that once one wants to directly access core (i.e. as soon as you want to use `Bridge().get_core()`), then pymmcore is a much more direct route).  I have found it surprising and a bit unfortunate that, as awesome as pycro-manager is, [the paper](https://rdcu.be/cghwk) omits mention of pymmcore entirely, leading to [comments like this](https://forum.image.sc/t/pycromanager-bridge-after-launching-mm2-from-python/55142/2) where people in the community are under the impression that pycro-manager is their _only_ option if they'd like to interact with micromanager's C layer via python.  So I think it would be great to rectify that a little bit (and throw a little more love towards pymmcore) in the micromanager documentation.

**Comment by henrypinkard** [comment]
> @henrypinkard can you make a suggestion of what to the pycromananger description?

"Pycromanager is a package for automated control of microscope hardware and customized data acquisition that provides access to the to various capabilities of micro-manager through python. It can be used in multiple ways: alongside Micro-manager and its GUI, independently using only python, or as an invisible backend data-acquisition system with customized GUIs or control of microscopes from other computers across a network. It contains a layer that automatically translates Java and Python, which allows all of the existing Java APIs and plugins of Micro-Manager to be called from a Python environment. Its acquisition system is capable of acquiring of acquiring data at multiple GB/s for hours at a time, integrating image processing into the data acquisition loop, and being customized for use with various modalities of microscopy."


> For headless mode however is there a reason to prefer pycromanager over pymmcore(-plus)? The faster data access and removal of ZMQ from the stack make pymmcore more appealing to me for that. (throwback to [micro-manager/pycro-manager#132](https://github.com/micro-manager/pycro-manager/issues/132))

The underlying libraries that the pycromanager acquisition system uses incorporate 5-10 years of know-how from multiple generations of micro-manager developers on how to make a high performance yet flexible acquisition system, gained from an enourmous amount of testing on many different types of systems. Some of these are documented, and some aren't. For example, saving data at [multiple GB/s for hours at a time](https://forum.image.sc/t/loading-micromanager-tif-series-into-napari/62398/16) in fault-tolerant format that can also be opened very fast. Or running acquisitions that don't fit in the channel/z/time/position paradigm like those used in diffraction tomography or other computational imaging techniques. It's all been stress tested enough to the point that the major bugs have been worked out, so for those looking to simply use it for experiments, and not hack any of the internals, pycromanager is a good choice.

I can certainly see that there are situations where it might be preferable to ditch the ZMQ layer. For example, running live mode with a high frame rate and big sensor won't be especially smooth until some improvements can be made to the core. On the other hand, for some users the ZMQ layer is essential for controlling across a network.

> Personally, I tend to agree very much with @ianhi, that the killer feature of pycro-manager is that it works directly with the existing MM gui.

For some, yes. For others, this is a nuisance that gets in the way of using other features (hence the development of headless mode).

Personally, I think the napari front-end is nicer and potentially more powerful, and I think it would be great to make that as interoperable with pycromanager as possible.

> I also agree with [micro-manager/pycro-manager#132 (comment)](https://github.com/micro-manager/pycro-manager/issues/132#issuecomment-731881340), that once one wants to directly access core (i.e. as soon as you want to use `Bridge().get_core()`), then pymmcore is a much more direct route)

Definitely more direct. Whether that is an advantage, or even matters depends on what you're doing.

> I have found it surprising and a bit unfortunate that, as awesome as pycro-manager is, [the paper](https://rdcu.be/cghwk) omits mention of pymmcore entirely, leading to [comments like this](https://forum.image.sc/t/pycromanager-bridge-after-launching-mm2-from-python/55142/2)

Sorry, wasn't intentional. pymmcore wasn't on my radar at the time, and none of the co-authors suggested adding it. But the focus of the paper was mostly on the high-level APIs anyway. This is because the vast majority of pycromanager sits at a different level of abstraction than the core. Pymmcore is more analagous to MMCoreJ than it is to pycromanager, and the latter was never explicitly mentioned in the paper either. By design, pycro-manager has minimal wrapping around the core, only automatically exposing it through the ZMQ layer (with your suggestion of [core callbacks](https://github.com/micro-manager/pycro-manager/pull/362) being the first and only exception to this). 

Now that I am aware of it, I think pymmcore is great! And I think much of its infrastructure will be essential for accessing a more powerful C layer from python in the future. 

Btw, I fixed the bug described in that post so hopefully that type of thing won't arise again.

My only concern, as I've mentioned previously, is the unnecessary creation of two separate high-level acquisition systems that do essentially the same thing. This makes things more confusing for users, duplicates our efforts, and splits the amount of testing for everything built atop them. I've tried very hard to add features to pycromanager that make this avoidable, and solve the quite annoying problems that arose in other java-python packages like python-bioformats. I think this works quite nicely now, and I hope you'll give it a try.

To me, it seems it should be possible to utilize pymmcore-plus and all its niceties with either pycromanager-zmq-mmcorej or mmcorepy as backends, which could perhaps resolve some of these problems.

> So I think it would be great to rectify that a little bit (and throw a little more love towards pymmcore) in the micromanager documentation.

Of course!


I'm happy to discuss this all more, but given the amount of time it took me to type of this novel of a reply, I think it would be more efficient to do so over zoom :). Anyone else following along welcome to join.

**Comment by marktsuchida** [comment]
Ok to merge? These changes are already a big improvement and more can always be added later.

**Comment by ianhi** [comment]
> Ok to merge? These changes are already a big improvement and more can always be added later. 

I haven't had time to incorporate the suggested updates to the pycromanager text, and may not for a bit. Maybe we can either: merge now and iterate on the pycromanager text in a future PR, or if someone has time they can feel to push

**Comment by henrypinkard** [comment]
I'll do it, later, go ahead

**Pull request merged**
