### PR TITLE
Add google analytics tag

### PR DESCRIPTION
**Pull request by henrypinkard**
So that we can keep track of how many people visit the docs to better assess Micro-Manager's impact

### CODE REVIEW

**Comment by marktsuchida** [comment]
I'm not sure about this.... There might be strong opinions from some quarters.
Have you thought about what the (real and perceived) privacy implications of this are for people visiting the site?
I think adding this also necessitates having a privacy policy.

I'm not saying that collecting page view stats is out of the question. But it needs to be done with some thought and legal compliance (and openness to our community).

**Comment by henrypinkard** [comment]
I mostly thought this could be a duplication of the [readthedocs analytics features](https://docs.readthedocs.io/en/stable/privacy-policy.html#google-analytics), which collects "simple, non-personally identifying information over time, such as your IP address, browser type, internet service provider, referring and exit pages, time stamp".  Its useful for know stuff people are looking at, and how the user. Google has browser extensions that allow people to opt out.

but you're right it probably would require a privacy policy since we host on our own rather than using readthedocs...

**Comment by henrypinkard** [comment]
Not worth the additional effort needed

**Comment by marktsuchida** [comment]
@henrypinkard In no way the same thing, but this might be of interest: https://github.com/micro-manager/micro-manager/graphs/traffic
Too bad they don't have something similar for GitHub Pages (as far as I can tell).

**Comment by nicost** [comment]
I also should be able to add it to Google Search Console by giving Google access to the DNS record.  That is also a bit scary, but may be worth it.

**Comment by nicost** [comment]
Can also work by adding a <meta name="google-site-verification" content="xxxxxxxx" /> in the header (which I believe is defined here: https://github.com/micro-manager/micro-manager.github.io/blob/main/_layouts/home.html.   I believe that to be non-obtrusive, but let me know otherwise.

**Comment by henrypinkard** [comment]
> @henrypinkard In no way the same thing, but this might be of interest: https://github.com/micro-manager/micro-manager/graphs/traffic

Thanks @marktsuchida , that is helpful!

> I also should be able to add it to Google Search Console by giving Google access to the DNS record. That is also a bit scary, but may be worth it.

What does that do? Tells you how many people visit it from google?

**Comment by nicost** [comment]
> What does that do? Tells you how many people visit it from google?

Google knows everything;)

**Pull request closed without merging**
